name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC",
            tag: gnu,
            cc: "gcc",
            cxx: "g++"
          }
          - {
            name: "Ubuntu Latest CLang",
            tag: "clang",
            cc: "clang",
            cxx: "clang++"
          }
  
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Get tags
      run: git fetch --tags origin
    
    - name: Install dependencies
      run: sudo apt install -y clang libboost-all-dev ninja-build qtbase5-dev libqt5svg5-dev python3-pip grep

    - name: Install conan
      run: sudo pip install conan

    - name: Install conan dependencies
      run: conan install . -s build_type=Release -of .conan/${{ matrix.config.cc }} --build=missing -pr:a .conan/${{ matrix.config.cc }}/profile

    - name: Configure CMake
      run: cmake --preset="ci_${{ matrix.config.tag }}_release"

    - name: Build
      run: cmake --build ${{github.workspace}}/build | tee ${{github.workspace}}/build/build.log

    - name: Count warnings
      run: grep -c "warning:" ${{github.workspace}}/build/build.log

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build